### ISSUE TITLE
Fantastic work!

### ISSUE THREAD

**Issue by satmandu** [jay0lee/chromeos-update-directory#1]
Any chance of automatically generating offsets for the filesystems within the recovery image URLs?

They appear to have the file magic mentioned here: https://chromium.googlesource.com/chromiumos/platform/dev-util/+/stabilize-4287.B/host/lib/update_payload/payload.py

**Comment by jay0lee** [comment]
What do you mean by offset? What information are you looking for?

**Comment by satmandu** [comment]
I'm trying to mount the RootFS partition stored inside the update images.

The Recovery images are just mountable to get a RootFS, but the update images appear to have some data tacked on.

The recovery images aren't updated very often, but the update images obviously update much more often.

I use the rootfs images to test builds against for the Chromebrew project inside docker containers. For instance there's a Glibc update to 2.32 from 2.27 in M92, and I've extracted my own RootFS from my own x86_64 Beta machine. But I don't have an arm64 machine, so I don't have a good way to easily get the RootFS for M92 for that series. But if I can just extract the RootFS easily from the update images, it's a completely different ball game. :)

**Comment by jay0lee** [comment]
Got it, so you need to grab a few tools from the Chrome OS SDK with a bit
clone:

https://github.com/jay0lee/chromeos-update-directory/blob/main/.github/workflows/updates.yml#L30

Then there's a script in that repo called paycheck that lets you extract
the Chrome OS root partition from a full update file (delta updates won't
work for obv reasons)

https://github.com/jay0lee/chromeos-update-directory/blob/c7bce39e8c3d8c210d3c2501f93b88c24404ec25/scripts/common.py#L88
