### ISSUE TITLE
Any way to get info for A/B testing images?

### ISSUE THREAD

**Issue by satmandu** [jay0lee/chromeos-update-directory#2]
e.g. kernelnext images only go out to some subset of machines during updates.

It would be useful to be able to get the image URLs for such updates.

**Comment by jay0lee** [comment]
What typically happens is these images roll out at 1%. The challenge then becomes the script would need to query for every single board/channel combo 100+ times to try and get that 1% special response. That's going to be very difficult to achieve from a performance standpoint and there's a good chance Google servers would see that activity as a DoS.

Unfortunately I don't see this as feasible right now.

**Comment by satmandu** [comment]
Thanks for explaining. That's quite reasonable.
