### ISSUE TITLE
Android version: Unknown

### ISSUE THREAD

**Issue by WesBosch** [jay0lee/chromeos-update-directory#5]
One of our mods in the r/chromeos community noticed Google has silently started rolling out Android 13 to some boards (Confirmed on Hatch so far, I haven't checked others yet) and noticed that it appears as "Unknown" in your data. Thought I'd give you a heads up!

Example of where this can be found:
https://github.com/jay0lee/chromeos-update-directory/blob/main/data/updates/hatch/dev/data.json

**Comment by Danik1601** [comment]
Will this be fixed by https://github.com/jay0lee/chromeos-update-directory/commit/735a0228162c6ff115e28bd573c9ffd7d1b09561 & https://github.com/jay0lee/chromeos-update-directory/commit/436367f9983390e57f295780995278ef52bb4183?

**Comment by jay0lee** [comment]
Yes, this is fixed now
